-- 환경 센서 (EnvSensor 엔티티). Hibernate 가 생성하는 DDL 과 동일하다. (ddl-auto=validate 통과)
CREATE TABLE safety.env_sensors (
    sensor_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    sensor_type character varying(20) NOT NULL,
    threshold_max numeric(10,2),
    threshold_min numeric(10,2),
    unit character varying(10) NOT NULL,
    zone_id bigint NOT NULL,
    CONSTRAINT env_sensors_sensor_type_check CHECK (((sensor_type)::text = ANY ((ARRAY['TEMPERATURE'::character varying, 'HUMIDITY'::character varying, 'FINE_DUST'::character varying, 'OXYGEN'::character varying, 'CHEMICAL'::character varying, 'NOISE'::character varying])::text[])))
);

ALTER TABLE safety.env_sensors ALTER COLUMN sensor_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME safety.env_sensors_sensor_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY safety.env_sensors ADD CONSTRAINT env_sensors_pkey PRIMARY KEY (sensor_id);

ALTER TABLE ONLY safety.env_sensors
    ADD CONSTRAINT fkg6h7nc4gmk5knnc1398lv53st FOREIGN KEY (zone_id) REFERENCES safety.zones(zone_id);

-- 구역별 센서 목록 조회와 구역 삭제 가드(count)가 zone_id 로 찾는다.
CREATE INDEX idx_env_sensors_zone ON safety.env_sensors USING btree (zone_id);
