CREATE SCHEMA IF NOT EXISTS safety;
-- Data API(anon/authenticated)에서 접근하지 못하게 한다. 백엔드는 postgres 역할로 접속한다.
REVOKE ALL ON SCHEMA safety FROM anon, authenticated;

CREATE TABLE safety.managers (
    manager_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    login_id character varying(50) NOT NULL,
    name character varying(30) NOT NULL,
    password character varying(255) NOT NULL,
    profile_image_url character varying(500),
    refresh_token character varying(500),
    refresh_token_expires_at timestamp(6) without time zone,
    role character varying(20) NOT NULL,
    CONSTRAINT managers_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying])::text[])))
);

ALTER TABLE safety.managers ALTER COLUMN manager_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME safety.managers_manager_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE safety.processes (
    process_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    name character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT processes_status_check CHECK (((status)::text = ANY ((ARRAY['RUNNING'::character varying, 'STOPPED'::character varying])::text[])))
);

ALTER TABLE safety.processes ALTER COLUMN process_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME safety.processes_process_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE safety.vital_records (
    vital_record_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    body_temp numeric(4,1),
    heart_rate integer,
    measured_at timestamp(6) without time zone NOT NULL,
    step_count integer,
    device_id bigint NOT NULL
);

ALTER TABLE safety.vital_records ALTER COLUMN vital_record_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME safety.vital_records_vital_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE safety.wearable_devices (
    device_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    battery_level integer,
    connection_status character varying(20) NOT NULL,
    device_type character varying(30) NOT NULL,
    last_synced_at timestamp(6) without time zone,
    serial_no character varying(50) NOT NULL,
    worker_id bigint,
    CONSTRAINT wearable_devices_connection_status_check CHECK (((connection_status)::text = ANY ((ARRAY['CONNECTED'::character varying, 'DISCONNECTED'::character varying, 'ERROR'::character varying, 'RETIRED'::character varying])::text[]))),
    CONSTRAINT wearable_devices_device_type_check CHECK (((device_type)::text = ANY ((ARRAY['BAND'::character varying, 'HELMET'::character varying, 'TAG'::character varying])::text[])))
);

ALTER TABLE safety.wearable_devices ALTER COLUMN device_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME safety.wearable_devices_device_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE safety.workers (
    worker_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    employee_no character varying(30) NOT NULL,
    name character varying(30) NOT NULL,
    safety_status character varying(20) NOT NULL,
    zone_id bigint,
    CONSTRAINT workers_safety_status_check CHECK (((safety_status)::text = ANY ((ARRAY['NORMAL'::character varying, 'CAUTION'::character varying, 'DANGER'::character varying, 'EMERGENCY'::character varying])::text[])))
);

ALTER TABLE safety.workers ALTER COLUMN worker_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME safety.workers_worker_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE safety.zones (
    zone_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    map_x numeric(8,2),
    map_y numeric(8,2),
    name character varying(50),
    zone_code character varying(10) NOT NULL,
    process_id bigint NOT NULL
);

ALTER TABLE safety.zones ALTER COLUMN zone_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME safety.zones_zone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY safety.managers
    ADD CONSTRAINT managers_pkey PRIMARY KEY (manager_id);

ALTER TABLE ONLY safety.processes
    ADD CONSTRAINT processes_pkey PRIMARY KEY (process_id);

ALTER TABLE ONLY safety.managers
    ADD CONSTRAINT uk_managers_login_id UNIQUE (login_id);

ALTER TABLE ONLY safety.wearable_devices
    ADD CONSTRAINT uk_wearable_devices_serial_no UNIQUE (serial_no);

ALTER TABLE ONLY safety.workers
    ADD CONSTRAINT uk_workers_employee_no UNIQUE (employee_no);

ALTER TABLE ONLY safety.zones
    ADD CONSTRAINT uk_zones_process_zone_code UNIQUE (process_id, zone_code);

ALTER TABLE ONLY safety.vital_records
    ADD CONSTRAINT vital_records_pkey PRIMARY KEY (vital_record_id);

ALTER TABLE ONLY safety.wearable_devices
    ADD CONSTRAINT wearable_devices_pkey PRIMARY KEY (device_id);

ALTER TABLE ONLY safety.workers
    ADD CONSTRAINT workers_pkey PRIMARY KEY (worker_id);

ALTER TABLE ONLY safety.zones
    ADD CONSTRAINT zones_pkey PRIMARY KEY (zone_id);

CREATE INDEX idx_vital_records_device_measured ON safety.vital_records USING btree (device_id, measured_at);

ALTER TABLE ONLY safety.wearable_devices
    ADD CONSTRAINT fk1xgo9be1w4ahlpk7s2k7ye2j FOREIGN KEY (worker_id) REFERENCES safety.workers(worker_id);

ALTER TABLE ONLY safety.vital_records
    ADD CONSTRAINT fk7rk0gvjwpn9jvoqwddhxg0lao FOREIGN KEY (device_id) REFERENCES safety.wearable_devices(device_id);

ALTER TABLE ONLY safety.zones
    ADD CONSTRAINT fkj0rilte8jc59x4l5u9ywqjkb7 FOREIGN KEY (process_id) REFERENCES safety.processes(process_id);

ALTER TABLE ONLY safety.workers
    ADD CONSTRAINT fkrqybl6ynoafuo1ix2s509lccc FOREIGN KEY (zone_id) REFERENCES safety.zones(zone_id);
